### PR TITLE
Added ThreadSafeWindow and ThreadSafeGlfw struct wrappers

### LINKED ISSUE #238: Limitations regarding Multithreading
The `Glfw` structure was implemented to enforce that some functions can only be called from the main thread. This structure seems to not been implemented right however: it is limiting function calls to perfectly thread-safe GLFW functions.  Examples of these are `make_context_current`, `get_time`, `set_time` and `set_swap_interval`. All of these functions are thread-safe, but for some reason rely on the `Glfw`-struct. 

A secondary issue is that the `Window` structure carries a copy of the `Glfw` structure. Even if we moved the thread-safe functions outside of the `Glfw` structure, we still wouldn't be able to call window-specific functions from other threads.

A good solution would be to copy the thread-safe functions outside of the `Glfw` structure, mark the `Glfw` ones as deprecated and make them call their moved equivalents. 

The `Window` structure cannot be fixed without breaking existing code however. People might have relied on there being a `Glfw` structure inside their windows, and thus taking it out will result in errors.

I am willing to do a pull-request for this, but I think this needs further discussion.

### LINKED ISSUE #386: Remove multithreading limitations
Currently there's no support for threading except for the rudimentary `RenderContext` abstraction, which gives access to three procedures to-do with OpenGL context.

Accessing the remainder of GLFW's thread-safe procedures takes something like this (or going straight to the FFI):
```rust
let render_thread = unsafe {
    // All this madness here is to make the compiler pass the GLFW object references
    // into the thread. This is "unsafe" in Rust sense but thraed-safe GLFW procedures
    // should work (see GLFW docs for a list).

    struct Wrapper(*mut glfw::Glfw, *mut glfw::Window);
    unsafe impl Send for Wrapper {}

    let mut wrapper = Wrapper(&mut glfw, &mut window);

    thread::spawn(move || {
        render(&mut *(wrapper.0), &mut *(wrapper.1));
    })
};
```
This obviously isn't ideal for Rust because of having to use `unsafe`.

Here's a complete list of procedures that should be available between threads: http://www.glfw.org/docs/latest/intro.html#thread_safety

I think a solution is to add a `GlfwThreadSafeProcs` and a `WindowThreadSafeProcs` types for accessing the entire list and to make them obtainable from `Glfw` and `Window` respectively.

### PR DESCRIPTION
**Pull request by bohdloss**
Added `ThreadSafeWindow` and `ThreadSafeGlfw` struct wrappers for `Window` and `Glfw` which contain only thread-safe glfw functions and can be shared between threads. This closes #386 , closes #238

### CODE REVIEW

**Comment by bvssvni** [comment]
@bohdloss can you rebase?

**Comment by bohdloss** [comment]
Sure, gimme a sec

**Comment by bohdloss** [comment]
please have patience, i am bad at using git :D

**Comment by bohdloss** [comment]
Ok i think i did it

**Comment by bohdloss** [comment]
It compiled, but tell me if there are any mistakes, this is the first time i solve a merge conflict lmao

**Comment by bvssvni** [comment]
Merging

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
