### PR TITLE
Fix travis build

### PR DESCRIPTION
**Pull request by aloucks**

### CODE REVIEW

**Comment by aloucks** [comment]
https://github.com/PistonDevelopers/glfw-rs/blob/master/examples/defaults.rs fails to link GL.

Maybe travis stopped installing it by default? `glfw_window` tests probably don't link to GL which is why they continue to pass.

https://github.com/PistonDevelopers/glfw-rs/blob/2c43ff47879d96ee889c99e03ced59eadb3924cc/examples/defaults.rs#L82-L84

**Comment by aloucks** [comment]
Fixes #418

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
