### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by coderedart**
fix a small typo in x11 raw window handle code

### CODE REVIEW

**Comment by coderedart** [comment]
@bvssvni there was a small typo in https://github.com/PistonDevelopers/glfw-rs/pull/524 .

**Comment by EriKWDev** [comment]
Maybe "typo" gives indication that it is the variable i.e. not important, but it is the type that is incorrect so it doesn't compile with X11 backend. @bvssvni

**Comment by bvssvni** [comment]
Merging

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
