### PR TITLE
Update raw_window_handle to version 0.5.0

### PR DESCRIPTION
**Pull request by nullfedora**
Fixes compatibility with wgpu.

### CODE REVIEW

**Comment by EriKWDev** [comment]
Pulled your pr and tried compiling with `cargo check` and got the following:
```console
error[E0433]: failed to resolve: use of undeclared type `XLibDisplayHandle`
    --> src/lib.rs:2991:26
     |
2991 |         let mut handle = XLibDisplayHandle::empty();
     |                          ^^^^^^^^^^^^^^^^^ use of undeclared type `XLibDisplayHandle`

error: unused import: `raw_window_handle::XlibDisplayHandle`
    --> src/lib.rs:2990:13
     |
2990 |         use raw_window_handle::XlibDisplayHandle;
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
note: the lint level is defined here
    --> src/lib.rs:24:5
     |
24   |     unused,
     |     ^^^^^^
     = note: `#[deny(unused_imports)]` implied by `#[deny(unused)]`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `glfw` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `glfw` due to 2 previous errors
```

**Comment by EriKWDev** [comment]
Also (might be unrelated to PR), but when compiling with the `wayland` feature enabled I get some whacky windows from the examples:

image

This might be 'intended' though thanks to libadwaita

**Comment by coderedart** [comment]
I get the same weird window issue on gnome as shown in the above screenshot, but on kde plasma wayland, everything works fine.

**Comment by bvssvni** [comment]
Merging

**Comment by bvssvni** [comment]
Thanks!

**Comment by EriKWDev** [comment]
You just merged and released a new version without fixing the compile error we mentioned?

**Comment by EriKWDev** [comment]
@bvssvni 

Sorry for spamming but you should probably see this

**Comment by bvssvni** [comment]
@EriKWDev thanks for noticing! I published 0.49.1 with the fix: https://crates.io/crates/glfw

**Pull request merged**
