### PR TITLE
Added set_x_callback set of functions

### LINKED ISSUE #441: Custom callbacks for window events
I would like to implement custom callbacks for window events. I am searching for a function  like set_key_callback in the c implementation. I tried to figure out how c binding in rust works and to implement it on my own in the glfw-rs sourcecode. Sadly I did not go far and do not really understand further than when the first *ffi* appears in the sourcecode. I do not know if the methods are left out intentionally and I am a rust newcomer and am so not 100 percent sure if there are language specific reasons for this. I hope I did not see any obvious reasons or notes why this is not implemented.

### LINKED ISSUE #492: Why not `Window::set_*_callback`?
`Window::set_*_polling` ultimately enables or disables a callback to something.

This callback just updates the `WindowEvent` in the receiver you get on `glfw.create_window`, so why not a safer function to set custom callbacks and optionally to set the default callback in `set_*_polling`?

That would allow custom behaviour without needing to match against a `WindowEvent`.

### PR DESCRIPTION
**Pull request by bohdloss**
Added a new set of set_x_callback functions parallel to set_x_polling set of functions. As of now, they are mutually exclusive, eg set_x_polling overwrites the effect of set_x_callback and vice versa. This closes #492 , closes #441

### CODE REVIEW

**Comment by bohdloss** [comment]
Now they should work seamlessly together. Sadly, i had to make a bit of a mess with macros to get this to work properly, so any feedback on how to improve this is appreciated. All original functions and structs have been preserved for backwards compatibility except the old polling callback macro system but that was not exposed to the end user anyways

**Comment by bvssvni** [comment]
Looks good to me!

**Comment by bvssvni** [comment]
I'm going on vacation tomorrow, will be back in a week. Feel free to make improvements in the meantime. If there are no objections, then I think we should merge it and release a new version.

**Comment by bohdloss** [comment]
The only thing i wanted to add is a reference to the `Window` struct in the callback arguments the user receives, but i can't get a reference to it nor find a reasonable way to contruct a new `Window` struct

**Comment by bohdloss** [comment]
I made it so (but did not commit the change yet) callback functions accept the window object as an argument, and can call mutable functions as well as do things like change the callback within the callback. The only problem with this patch is it changes what is returned by `create_window_intern()` from `Option<(Window, Receiver<(f64, WindowEvent)>)>` to `Option<(Box<Window>, Receiver<(f64, WindowEvent)>)>`. Let me know if this is acceptable before merging, and if it is i will commit it.

**Comment by bohdloss** [comment]
The alternative to this would require the user to do something like wrap the `Window` object created by `create_window` in an `Rc` or something similar and capture a `Weak` in the callback. The former makes it a bit more intuitive, the latter gives the user more control (and doesn't require any additional work, it would already work in the current state).

**Comment by bohdloss** [comment]
To better illustrate what I'm trying to say:

Alternative 1: (not yet implemented)
```
let mut glfw = glfw::init(glfw::FAIL_ON_ERRORS).unwrap();

// Window returned is wrapped in a `Box<Window>`
let (mut window /*: Box<Window>*/, events) = glfw.create_window(300, 300, "Callback testing!", glfw::WindowMode::Windowed)
    .expect("Failed to create GLFW window.");
window.make_current();

// This allows (through some shenanigans) for the callback function
// to be able to receive `window: &mut Window` as an argument
window.set_key_callback(|window /*: &mut Window*/, key, scancode, action, mods| {
    match key {
        Key::Escape => window.set_should_close(true),
        _ => {}
}

// Window loop code...
```

Alternative 2:
```
let mut glfw = glfw::init(glfw::FAIL_ON_ERRORS).unwrap();

// Window is returned as a `Window` as usual
let (mut window /*: Window*/, events) = glfw.create_window(300, 300, "Callback testing!", glfw::WindowMode::Windowed)
    .expect("Failed to create GLFW window.");
window.make_current();

// Then the window must be wrapped in a `Rc` to be passed to the callback
let window_rc: Rc<RefCell<Window>> = Rc::new(RefCell::new(window));

// The callback then captures the `Weak`
let window_weak: Weak<RefCell<Window>> = Rc::downgrade(&window_rc);
window_rc.borrow_mut().set_key_callback(move |key, scancode, action, mods| {
    match key {
        Key::Escape => window_weak.borrow_mut().set_should_close(true),
        _ => {}
}

// Window loop code...
```

**Comment by bvssvni** [comment]
I think using `Box` is fine.

**Comment by bohdloss** [comment]
The change is now in place and this PR is ready to merge whenever you want!

**Comment by bohdloss** [comment]
I just found a problem: if the user takes the window object out of the `Box` and onto the stack, not only will the callbacks stop working, but invalid memory will be accessed leading to undefined behavior. I was thinking of using a `Pin<Box<Window>>` to ensure the `Window` cannot be taken out of the box.

**Comment by bohdloss** [comment]
I unfortunately had to revert that change because it prevents the user from acquiring a mutable reference to the window. For now i think it's good to just advise the user not to unbox the window, instead of adding more layers of complexity

**Comment by bohdloss** [comment]
Since the use of `Box` can be a breaking change, i propose making a new feature for this called `glfw-callbacks` which can be optionally enabled by the user. Callbacks will still work but will lack the `&mut Window` argument unless the feature is enabled

**Comment by bvssvni** [comment]
Merging

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
